import Head from 'next/head'
// import Image from 'next/image'
import styles from '../sandBoxTesting/styles.module.css'
// import { myCanva } from '../sandBoxTesting/canva.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="/sandBoxTesting/styles.css" />
      </Head>
      <body id='create'>
        <h3>Canva App</h3>
        <h6>Edit Mode</h6>
        <canvas onLoad="myCanva()" id="canvas" width="600" height="600"></canvas>
        <script src="/sandBoxTesting/canva.js">
        </script>
      </body>
    </div>
  )
}
