import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Deck from '../components/deck/deck'


export default function Home() {
  return (<>
    <body className={styles.container}>
      <Head>
        <title>myNext-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="cards">
        <h1> jScript.Poker </h1>
        <p></p>
        <Deck title="game" path="game/" turned="2" />

        <Deck title="hand" path="2/" turned="2" />

        <Deck title="deck" path="fullDeck/" turned="2" />

      </div>
    </body>
  </>)
}
