// import Image from 'next/image'
import { ApolloClient, gql, InMemoryCache } from '@apollo/client'
import Head from 'next/head';
import styles from '../styles/Home.module.scss';

// import Deck from "./../lib/main";
import Cards from "../components/deck/deck";
// import { func } from 'prop-types';


const client = new ApolloClient({
  uri: 'http://localhost:4000/',
  cache: new InMemoryCache(),
});

const gameQuery = gql`
        query {
          game {
            number
            symbol
          }
        }
      `

const getCardsQuery = gql`query GetCards($cards: Int){
          getCards(cards: $cards) {
            symbol
            number
          }
        }`

const fullNewDeckQuery = gql`
      query {
        newDeck {
          number
          symbol
        }
      }
    `


export default function Home({ title, game, hand, fullDeck }) {
  return (<>
    <body className={styles.home}>
      <Head>
        <title>myNext-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.cards}>
        <h1 className={styles.title}>{title}</h1>
        <p></p>
        <h3 className={styles.title}>Game</h3>
        <Cards title="game" cards={game} turned="2" />

        <h3 className={styles.title}>Hand</h3>
        <Cards title="hand" cards={hand} turned="2" />

        <h3 className={styles.title}>New Deck</h3>
        <Cards title="deck" cards={fullDeck} turned="0" />

      </div>
    </body>
  </>)
}


export async function getServerSideProps(context) {
  const gameData = await client.query({ query: gameQuery });
  const handData = await client.query({
    query: getCardsQuery,
    variables: { cards: 2 },
    fetchPolicy: 'no-cache'
  });
  const newData = await client.query({ query: fullNewDeckQuery });

  return {
    props: {
      title: 'jScript.Casino',
      game: gameData.data.game,
      hand: handData.data.getCards,
      fullDeck: newData.data.newDeck,
    }
  }
}



// export async function getServerSideProps(context) {
//   const deck = new Deck();
//   const game = deck.fetchDeck(5);
//   const hand = deck.fetchDeck(2);
//   const deck2 = new Deck();
//   const fullDeck = deck2.cards

//   return {
//     props: {
//       title: 'jScript.Casino',
//       game,
//       hand,
//       fullDeck
//     }
//   }
// }


// export async function getServerSideProps(context) {
//   const gameData = await (await fetch('http://localhost:4000', {
//     method: 'POST',
//     headers: {
//       'Content-Type': 'application/json'
//     },
//     body: JSON.stringify({
//       query: `
//         query {
//           game {
//             number
//             symbol
//           }
//         }
//       `
//     })
//   })).json();

//   const handData = await (await fetch('http://localhost:4000', {
//     method: 'POST',
//     headers: {
//       'Content-Type': 'application/json'
//     },
//     body: JSON.stringify({
//       query: `query GetCards($cards: Int){
//         getCards(cards: $cards) {
//           symbol
//           number
//         }
//       }`,
//       variables: {
//         cards: 2
//       }
//     })
//   })).json();

//   const newData = await (await fetch('http://localhost:4000', {
//     method: 'POST',
//     headers: {
//       'Content-Type': 'application/json'
//     },
//     body: JSON.stringify({
//       query: `
//       query {
//         newDeck {
//           number
//           symbol
//         }
//       }
//     `
//     })
//   })).json();