import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Deck } from './../components/deck/deck.js'


export default function Home() {
  return (<>
    <div className={styles.container}>
      <Head>
        <title>myNext-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="cards">
        <h1> jScript.Poker </h1>
        <p>
        </p>
        <Deck title="game" path="game/" turned="2" />
        <Deck title="hand" path="game/2" turned="2" />
      </div >
    </div>
  </>)
}
